name: Lint code
on:
  push:
  pull_request:

jobs:
  PythonBlack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check code lints with Black
        uses: psf/black@stable

  Prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: Install Prettier
        run: npm install -g prettier

      - name: Run Prettier --check
        run: prettier --check ${GITHUB_WORKSPACE}
